# Generated by Django 3.0.8 on 2020-09-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200919_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcolumn',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_column', to='api.Project'),
        ),
    ]
