# Generated by Django 3.0.8 on 2020-11-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201115_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenufile',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menus', to='api.Restaurant'),
        ),
    ]
