# Generated by Django 3.0.8 on 2020-11-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201116_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantimagefile',
            old_name='file',
            new_name='img_file',
        ),
        migrations.RenameField(
            model_name='restaurantmenufile',
            old_name='file',
            new_name='menu_file',
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0, null=True),
        ),
    ]
